<?xml version="1.0" encoding="UTF-8"?>
<ilog.rules.studio.model.brl:ActionRule xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:ilog.rules.studio.model.brl="http://ilog.rules.studio/model/brl.ecore">
  <name>output-default-setting</name>
  <uuid>81c2955e-819c-4f6a-95de-ef1e791144e9</uuid>
  <locale>en_US</locale>
  <definition><![CDATA[set decision to "Sorry but we don't have enough information." ;]]></definition>
</ilog.rules.studio.model.brl:ActionRule>
